
import numpy as np
import matplotlib.pyplot as plt
import matplotlib



funcion=np.genfromtxt("OrbitaEuler.txt")
f=np.transpose(funcion)

plt.figure()
plt.plot(f[0],f[1],color="r")
plt.title("Respecto a x")
plt.xlabel("x")
plt.ylabel("A")
plt.show()
plt.savefig("x.png")
print(np.size(funcion))
print (f)
plt.close()

plt.figure()
plt.plot(f[0],f[2],color="r")
plt.title("Respecto a y")
plt.xlabel("x")
plt.ylabel("A")
plt.show()
plt.savefig("y.png")
print(np.size(funcion))
print (f)
plt.close()

plt.figure()
plt.plot(f[1],f[2],color="r")
plt.title("x y")
plt.xlabel("x")
plt.ylabel("A")
plt.show()
plt.savefig("xy.png")
print(np.size(funcion))
print (f)
plt.close()

funcion=np.genfromtxt("OrbitaLF.txt")
f=np.transpose(funcion)
plt.figure()
plt.plot(f[0],f[1],color="r")
plt.title("Respecto a x")
plt.xlabel("x")
plt.ylabel("A")
plt.show()
plt.savefig("xlf.png")
print(np.size(funcion))
print (f)
plt.close()

plt.figure()
plt.plot(f[0],f[2],color="r")
plt.title("Respecto a y")
plt.xlabel("x")
plt.ylabel("A")
plt.show()
plt.savefig("ylf.png")
print(np.size(funcion))
print (f)
plt.close()

plt.figure()
plt.plot(f[1],f[2],color="r")
plt.title("x y")
plt.xlabel("x")
plt.ylabel("A")
plt.show()
plt.savefig("xylf.png")
print(np.size(funcion))
print (f)
plt.close()

funcion=np.genfromtxt("OrbitaRK.txt")
f=np.transpose(funcion)
plt.figure()
plt.plot(f[0],f[1],color="r")
plt.title("Respecto a x")
plt.xlabel("x")
plt.ylabel("A")
plt.show()
plt.savefig("xrk.png")
print(np.size(funcion))
print (f)
plt.close()

plt.figure()
plt.plot(f[0],f[2],color="r")
plt.title("Respecto a y")
plt.xlabel("x")
plt.ylabel("A")
plt.show()
plt.savefig("yrk.png")
print(np.size(funcion))
print (f)
plt.close()

plt.figure()
plt.plot(f[1],f[2],color="r")
plt.title("x y")
plt.xlabel("x")
plt.ylabel("A")
plt.show()
plt.savefig("xyrk.png")
print(np.size(funcion))
print (f)
plt.close()

